# Generated by Django 4.0.1 on 2022-01-14 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('distance_in_km', models.IntegerField()),
                ('distance_description', models.CharField(choices=[('close', 'close'), ('near', 'near'), ('far', 'far')], default='close', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('fuel_consumption', models.CharField(choices=[('low', 'low'), ('fair', 'fair'), ('high', 'high')], default='low', max_length=100)),
                ('plate_number', models.CharField(max_length=100)),
                ('seat_capacity', models.CharField(max_length=100)),
                ('in_use', models.BooleanField(default=True)),
                ('condition', models.CharField(choices=[('bad', 'bad'), ('fair', 'fair'), ('good', 'good')], default='good', max_length=100)),
                ('under_maintenance', models.BooleanField(default=True)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_passengers', models.IntegerField()),
                ('driver', models.CharField(max_length=100)),
                ('date_of_journey', models.DateField()),
                ('vehicle_condition', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='vehicle.bus')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='vehicle.location')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
