# Generated by Django 4.0.1 on 2022-01-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='distance_description',
            field=models.CharField(choices=[('close', 'close'), ('average', 'average'), ('far', 'far')], default='close', max_length=100),
        ),
    ]
