# Generated by Django 4.0.1 on 2022-01-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_alter_location_distance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_capacity',
            field=models.IntegerField(),
        ),
    ]
